ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - grafana.momo.dtc.tatar
  path: /
  pathType: Prefix
  tls:
    - secretName: grafana-server-tls
      hosts:
        - grafana.momo.dtc.tatar