server:
  persistentVolume:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - prometheus.momo.dtc.tatar
    path: /
    pathType: Prefix
    tls:
      - secretName: prometheus-server-tls
        hosts:
          - prometheus.momo.dtc.tatar